language: python

python:
  - "3.5"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  - python setup.py develop
  - make syntax
  - pytest --cov-report term-missing --cov=aioredlock -sv tests/ut
  - docker-compose -f docker-compose.yml up -d
  - pytest -sv tests/acceptance
  - docker-compose -f docker-compose.yml stop

after_success:
  - codecov
